# Not To Do List API

@baseUrl = http://localhost:8000/api/v1/tasks



### POST the task list
POST  {{baseUrl}}
Content-Type: application/json

{
  "id": 3,
  "task": "Selling",
  "hour": 5
}

### GET the task list
GET {{baseUrl}}


### GET the task list
GET {{baseUrl}}/singleTask?id=2

### UPDATE the task list
PUT {{baseUrl}}
Content-Type: application/json

{
  "id": 1,
  "hour": 10
}

### DELETE the task list
DELETE  {{baseUrl}}/1
Content-Type: application/json

{
  "id": 1
}